### ISSUE TITLE
关于增加mermaid支持的建议

### ISSUE THREAD

**Issue by Lynchrocket** [hooozen/hexo-theme-tranquility#34]
作者大大，新年快乐！
增加mermaid能加强markdown的表达能力，能让博客编写者快速绘图。
可使用[hexo-filter-mermaid-diagrams](https://github.com/webappdevelp/hexo-filter-mermaid-diagrams)这个项目。具体做法如下：
1. 安装插件 `npm install hexo-filter-mermaid-diagrams`
2. 修改配置：在 `_config.yml` 或者 `_config.tranquility.yml` 中增加
```
# mermaid chart https://github.com/knsv/mermaid
mermaid:
  enable: true
  version: latest
  options: 
    startOnload: true
```
3. 在 themes/tranquility/layout/post.njk 中增加（只需要增加两个省略号之间的部分就好）
```
{% block body %}
……
    {% if theme.mermaid.enable %}
      <script src='https://unpkg.com/mermaid@{{ theme.mermaid.version }}/dist/mermaid.min.js'></script>
      <script>
        if (window.mermaid) {
          mermaid.initialize({{ theme.mermaid.options }});
        }
      </script>
    {% endif %}
……
{% endblock body %}
```
4. 然后就能在markdown文章中绘图了
```mermaid
graph LR
  A --> B
  A --> D
```
